# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TF5w0J1S1nDRocrtHZo-CK5zocSpEOW
"""

a=int(input())
b=int(input())
c=int(input())
t=a+b+c
if(t>50):print(t-t/10)
else:print(t)